---

#- name: Create management user
#  action: command /usr/java/keycloak/bin/add-user-keycloak.sh -r master -u {{ keycloak_management_user }} -p {{ keycloak_management_password }}
#  ignore_errors: yes
##  notify: restart keycloak

#- name: keycloak systemd service enable and start
#  service:
#    name: keycloak
#    state: restarted

- name: Configure credentials
  action: command /usr/java/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user {{ keycloak_management_user }} --password {{ keycloak_management_password }}

- name: Create a new realm
  action: command /usr/java/keycloak/bin/kcadm.sh create realms -s realm={{ keycloak_app_realm }} -s enabled=true -o
  ignore_errors: yes

- name: Create a new client
  action: command /usr/java/keycloak/bin/kcadm.sh create clients -r {{ keycloak_app_realm }} -s clientId={{ keycloak_app_client_id }} -s enabled=true -o
  ignore_errors: yes

- name: Create a new user
  action: command /usr/java/keycloak/bin/kcadm.sh create users -r {{ keycloak_app_realm }} -s username={{ keycloak_app_user_demo_username }} -s enabled=true -i
  register: user_id
  ignore_errors: yes

- name: Change user's password
  action: command /usr/java/keycloak/bin/kcadm.sh update users/{{user_id.stdout}}/reset-password -r {{ keycloak_app_realm }} -s type=password -s value={{ keycloak_app_user_demo_password }} -s temporary=false -n
  ignore_errors: yes

