version: 2


jobs:
  build:
     
    working_directory: ~/knightrider

    machine:
      timezone:
        Europe/Madrid
      java:
        version: openjdk8

    steps: 

      - checkout

      - run: 
          name: Execute Maven
          command: mvn clean compile package -DskipTests

