---

- name: Descargamos el proyecto Apache Tomcat
  get_url: url=http://apache.rediris.es/tomcat/tomcat-8/v8.5.20/bin/apache-tomcat-8.5.20.tar.gz dest=/root/software/apache-tomcat-8.5.20.tar.gz

- name: Descomprimimos el proyecto Apache Tomcat
  unarchive: src=/root/software/apache-tomcat-8.5.20.tar.gz dest=/usr/java copy=no

- name: Creamos link para Apache Tomcat
  file: path=/usr/java/apache-tomcat src=/usr/java/apache-tomcat-8.5.20 state=link

- name: Anyadimos el grupo "tomcat"
  group: name=tomcat

- name: Anyadimos el usuario "tomcat"
  user: name=tomcat group=tomcat home=/usr/java/apache-tomcat

- name: Descargamos el adaptador de Keycloak para Apache Tomcat
  get_url: url=https://downloads.jboss.org/keycloak/3.3.0.CR2/adapters/keycloak-oidc/keycloak-tomcat8-adapter-dist-3.3.0.CR2.tar.gz dest=/root/software/keycloak-tomcat8-adapter-dist-3.3.0.CR2.tar.gz 

- name: Descomprimimos el adaptador de Keycloak para Apache Tomcat 8
  unarchive: src=/root/software/keycloak-tomcat8-adapter-dist-3.3.0.CR2.tar.gz dest=/usr/java/apache-tomcat/lib copy=no

- name: Cambiamos el propietario de la instalación Apache Tomcat
  file: path=/usr/java/apache-tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- template:
    owner=tomcat group=tomcat 
    src=server.xml.jk2
    dest=/usr/java/apache-tomcat/conf/server.xml

- template:
    owner=root group=root mode=0644
    src=tomcat.service.jk2
    dest=/etc/systemd/system/tomcat.service

- name: tomcat systemd service enable and start
  service: name=tomcat
           enabled=yes
           state=started

- name: Habilitar firewalld
  service: name=firewalld state=started enabled=yes

- name: Habilita los puertos en el firewall
  firewalld: 
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: 
    - 8080/tcp
    - 8443/tcp
  notify: restart firewalld

- name: Wait 300 seconds for port 8080 to become open on the host, don't start checking for 60 seconds
  wait_for:
    port: 8080
    delay: 60

